/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './article-details.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../article.service';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/forms/src/directives/ng_form';
import * as import16 from '@angular/forms/src/directives/ng_control_status';
import * as import17 from '@angular/forms/src/directives/default_value_accessor';
import * as import18 from '@angular/forms/src/directives/validators';
import * as import19 from '@angular/forms/src/directives/ng_model';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/forms/src/validators';
import * as import22 from '@angular/forms/src/directives/control_value_accessor';
import * as import23 from '@angular/forms/src/directives/ng_control';
import * as import24 from '@angular/forms/src/directives/control_container';
var renderType_ArticleDetailsComponent_Host:import0.RenderComponentType = (null as any);
class _View_ArticleDetailsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ArticleDetailsComponent_0_4:import3.ArticleDetailsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArticleDetailsComponent_Host0,renderType_ArticleDetailsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-articlelist',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ArticleDetailsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ArticleDetailsComponent_0_4 = new import3.ArticleDetailsComponent(this.parentInjector.get(import8.ArticleService),this.parentInjector.get(import9.ActivatedRoute),this.parentInjector.get(import10.Router));
    this._appEl_0.initComponent(this._ArticleDetailsComponent_0_4,[],compView_0);
    compView_0.create(this._ArticleDetailsComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ArticleDetailsComponent) && (0 === requestNodeIndex))) { return this._ArticleDetailsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ArticleDetailsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ArticleDetailsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ArticleDetailsComponent_Host === (null as any))) { (renderType_ArticleDetailsComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_ArticleDetailsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ArticleDetailsComponentNgFactory:import12.ComponentFactory<import3.ArticleDetailsComponent> = new import12.ComponentFactory<import3.ArticleDetailsComponent>('app-articlelist',viewFactory_ArticleDetailsComponent_Host0,import3.ArticleDetailsComponent);
const styles_ArticleDetailsComponent:any[] = ['.panel-body[_ngcontent-%COMP%] {\n            font-family: Lato, sans-serif;\n        }\n        .author[_ngcontent-%COMP%] {\n            display: inline-block;\n            font-style: italic;\n            font-size: 12px;\n            width:80%;\n        }\n        .config[_ngcontent-%COMP%] {\n            display: inline-block;\n            text-align: right;\n            font-size: 12px;\n            width: 19%;\n        }\n        .article-title[_ngcontent-%COMP%]{\n                text-transform: capitalize;\n        }'];
var renderType_ArticleDetailsComponent:import0.RenderComponentType = (null as any);
class _View_ArticleDetailsComponent0 extends import1.AppView<import3.ArticleDetailsComponent> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import13.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import13.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArticleDetailsComponent0,renderType_ArticleDetailsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-8 col-md-offset-2');
    this._text_1 = this.renderer.createText(this._el_0,' \n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import14.TemplateRef_(this._appEl_2,viewFactory_ArticleDetailsComponent1);
    this._NgIf_2_6 = new import13.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n        \n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import14.TemplateRef_(this._appEl_4,viewFactory_ArticleDetailsComponent3);
    this._NgIf_4_6 = new import13.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n        \n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import13.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import14.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import13.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:boolean = !this.context.isOnEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.isOnEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ArticleDetailsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ArticleDetailsComponent> {
  if ((renderType_ArticleDetailsComponent === (null as any))) { (renderType_ArticleDetailsComponent = viewUtils.createRenderComponentType('C:/Users/ahooshmand/Projects/MEAN/SmarGrid2/assets/app/components/article/articledetails/article-details.component.html',0,import11.ViewEncapsulation.Emulated,styles_ArticleDetailsComponent,{})); }
  return new _View_ArticleDetailsComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ArticleDetailsComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import13.NgIf;
  _text_19:any;
  _text_20:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArticleDetailsComponent1,renderType_ArticleDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'article',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','panel panel-default');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','panel-body');
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','article-title');
    this._text_5 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'strong',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,' ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'br',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'    \n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'footer',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','panel-footer');
    this._text_14 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','author');
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._appEl_18 = new import2.AppElement(18,13,this,this._anchor_18);
    this._TemplateRef_18_5 = new import14.TemplateRef_(this._appEl_18,viewFactory_ArticleDetailsComponent2);
    this._NgIf_18_6 = new import13.NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._text_20
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import13.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = this.parent.context.belongsToUser();
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_18_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.article.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'\n                ',this.parent.context.article.content,'\n            ');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_11,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(2,'\n                        Author: ',this.parent.context.article.username,', ',this.parent.context.article.articleId,'\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_16,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ArticleDetailsComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArticleDetailsComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ArticleDetailsComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArticleDetailsComponent2,renderType_ArticleDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','config');
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Edit',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Delete',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.onEdit()) !== false);
    return (true && pd_0);
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.onDelete()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ArticleDetailsComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArticleDetailsComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ArticleDetailsComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgForm_2_3:import15.NgForm;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import16.NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _DefaultValueAccessor_9_3:import17.DefaultValueAccessor;
  _RequiredValidator_9_4:import18.RequiredValidator;
  _NG_VALIDATORS_9_5:any[];
  _NG_VALUE_ACCESSOR_9_6:any[];
  _NgModel_9_7:import19.NgModel;
  _NgControl_9_8:any;
  _NgControlStatus_9_9:import16.NgControlStatus;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _DefaultValueAccessor_16_3:import17.DefaultValueAccessor;
  _RequiredValidator_16_4:import18.RequiredValidator;
  _NG_VALIDATORS_16_5:any[];
  _NG_VALUE_ACCESSOR_16_6:any[];
  _NgModel_16_7:import19.NgModel;
  _NgControl_16_8:any;
  _NgControlStatus_16_9:import16.NgControlStatus;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArticleDetailsComponent3,renderType_ArticleDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_2_3 = new import15.NgForm((null as any),(null as any));
    this._ControlContainer_2_4 = this._NgForm_2_3;
    this._NgControlStatusGroup_2_5 = new import16.NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','form-group');
    this._text_5 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'label',(null as any));
    this.renderer.setElementAttribute(this._el_6,'for','title');
    this._text_7 = this.renderer.createText(this._el_6,'Title',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','form-control');
    this.renderer.setElementAttribute(this._el_9,'name','title');
    this.renderer.setElementAttribute(this._el_9,'required','');
    this.renderer.setElementAttribute(this._el_9,'rows','2');
    this._DefaultValueAccessor_9_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_9));
    this._RequiredValidator_9_4 = new import18.RequiredValidator();
    this._NG_VALIDATORS_9_5 = [this._RequiredValidator_9_4];
    this._NG_VALUE_ACCESSOR_9_6 = [this._DefaultValueAccessor_9_3];
    this._NgModel_9_7 = new import19.NgModel(this._ControlContainer_2_4,this._NG_VALIDATORS_9_5,(null as any),this._NG_VALUE_ACCESSOR_9_6);
    this._NgControl_9_8 = this._NgModel_9_7;
    this._NgControlStatus_9_9 = new import16.NgControlStatus(this._NgControl_9_8);
    this._el_10 = this.renderer.createElement(this._el_4,'br',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'label',(null as any));
    this.renderer.setElementAttribute(this._el_12,'for','content');
    this._text_13 = this.renderer.createText(this._el_12,'Content',(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_4,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-control');
    this.renderer.setElementAttribute(this._el_16,'name','content');
    this.renderer.setElementAttribute(this._el_16,'required','');
    this.renderer.setElementAttribute(this._el_16,'rows','15');
    this._DefaultValueAccessor_16_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_16));
    this._RequiredValidator_16_4 = new import18.RequiredValidator();
    this._NG_VALIDATORS_16_5 = [this._RequiredValidator_16_4];
    this._NG_VALUE_ACCESSOR_16_6 = [this._DefaultValueAccessor_16_3];
    this._NgModel_16_7 = new import19.NgModel(this._ControlContainer_2_4,this._NG_VALIDATORS_16_5,(null as any),this._NG_VALUE_ACCESSOR_16_6);
    this._NgControl_16_8 = this._NgModel_16_7;
    this._NgControlStatus_16_9 = new import16.NgControlStatus(this._NgControl_16_8);
    this._el_17 = this.renderer.createElement(this._el_4,'br',(null as any));
    this._text_18 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_19,'type','submit');
    this._text_20 = this.renderer.createText(this._el_19,'Save',(null as any));
    this._text_21 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','btn btn-primary');
    this._text_25 = this.renderer.createText(this._el_24,'Cancel',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'ngSubmit',this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'submit',this.eventHandler(this._handle_submit_2_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'reset',this.eventHandler(this._handle_reset_2_2.bind(this)));
    const subscription_0:any = this._NgForm_2_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_9,'ngModelChange',this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_9,'input',this.eventHandler(this._handle_input_9_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_9,'blur',this.eventHandler(this._handle_blur_9_2.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_9_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_16,'ngModelChange',this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_16,'input',this.eventHandler(this._handle_input_16_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_16,'blur',this.eventHandler(this._handle_blur_16_2.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_16_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.DefaultValueAccessor) && (9 === requestNodeIndex))) { return this._DefaultValueAccessor_9_3; }
    if (((token === import18.RequiredValidator) && (9 === requestNodeIndex))) { return this._RequiredValidator_9_4; }
    if (((token === import21.NG_VALIDATORS) && (9 === requestNodeIndex))) { return this._NG_VALIDATORS_9_5; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_6; }
    if (((token === import19.NgModel) && (9 === requestNodeIndex))) { return this._NgModel_9_7; }
    if (((token === import23.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_8; }
    if (((token === import16.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_9; }
    if (((token === import17.DefaultValueAccessor) && (16 === requestNodeIndex))) { return this._DefaultValueAccessor_16_3; }
    if (((token === import18.RequiredValidator) && (16 === requestNodeIndex))) { return this._RequiredValidator_16_4; }
    if (((token === import21.NG_VALIDATORS) && (16 === requestNodeIndex))) { return this._NG_VALIDATORS_16_5; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (16 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_16_6; }
    if (((token === import19.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_7; }
    if (((token === import23.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_8; }
    if (((token === import16.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_9; }
    if (((token === import15.NgForm) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgForm_2_3; }
    if (((token === import24.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ControlContainer_2_4; }
    if (((token === import16.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgControlStatusGroup_2_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_12:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._RequiredValidator_9_4.required = currVal_12;
      this._expr_12 = currVal_12;
    }
    changes = (null as any);
    const currVal_14:any = 'title';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_9_7.name = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.parent.context.article.title;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgModel_9_7.model = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._NgModel_9_7.ngOnChanges(changes); }
    const currVal_25:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._RequiredValidator_16_4.required = currVal_25;
      this._expr_25 = currVal_25;
    }
    changes = (null as any);
    const currVal_27:any = 'content';
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgModel_16_7.name = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this.parent.context.article.content;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._NgModel_16_7.model = currVal_28;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_28,currVal_28);
      this._expr_28 = currVal_28;
    }
    if ((changes !== (null as any))) { this._NgModel_16_7.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_2_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_2_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_2_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_2_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_2_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_2,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_2_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_2,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_13:any = (this._RequiredValidator_9_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_9,'required',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = this._NgControlStatus_9_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_9,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_9_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_9,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_9_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_9,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_9_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_9,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_9_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_9,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_9_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_9,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_26:any = (this._RequiredValidator_16_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementAttribute(this._el_16,'required',((currVal_26 == (null as any))? (null as any): currVal_26.toString()));
      this._expr_26 = currVal_26;
    }
    const currVal_29:any = this._NgControlStatus_16_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_16_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_16_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_16_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_16_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_16_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_34);
      this._expr_34 = currVal_34;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_9_7.ngOnDestroy();
    this._NgModel_16_7.ngOnDestroy();
  }
  private _handle_ngSubmit_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onSaveEdit(this._NgForm_2_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_2_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_2_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_2_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.article.title = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_9_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_9_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_9_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_9_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.article.content = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_16_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_16_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_16_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_16_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onCancelEdit()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ArticleDetailsComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ArticleDetailsComponent3(viewUtils,parentInjector,declarationEl);
}