/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from './components/article/article.service';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from './components/error/error.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/router/src/directives/router_link';
import * as import14 from '@angular/router/src/directives/router_link_active';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/router/src/directives/router_outlet';
import * as import17 from './components/error/error.component';
import * as import18 from '@angular/router/src/router';
import * as import19 from '@angular/router/src/router_state';
import * as import20 from '@angular/common/src/location/location_strategy';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/router/src/router_outlet_map';
import * as import23 from '@angular/core/src/linker/component_factory_resolver';
import * as import24 from './components/error/error.component.ngfactory';
import * as import25 from '@angular/core/src/security';
var renderType_AppComponent_Host:import0.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AppComponent_0_4:import3.AppComponent;
  __ArticleService_0_5:import4.ArticleService;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  get _ArticleService_0_5():import4.ArticleService {
    if ((this.__ArticleService_0_5 == (null as any))) { (this.__ArticleService_0_5 = new import4.ArticleService(this.parentInjector.get(import9.Http),this.parentInjector.get(import10.ErrorService))); }
    return this.__ArticleService_0_5;
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new import3.AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4,[],compView_0);
    compView_0.create(this._AppComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4; }
    if (((token === import4.ArticleService) && (0 === requestNodeIndex))) { return this._ArticleService_0_5; }
    return notFoundResult;
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import12.ComponentFactory<import3.AppComponent> = new import12.ComponentFactory<import3.AppComponent>('my-app',viewFactory_AppComponent_Host0,import3.AppComponent);
const styles_AppComponent:any[] = [];
var renderType_AppComponent:import0.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import3.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import13.RouterLinkWithHref;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _RouterLinkActive_27_3:import14.RouterLinkActive;
  _query_RouterLink_27_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_27_1:import15.QueryList<any>;
  _el_28:any;
  _RouterLinkWithHref_28_3:import13.RouterLinkWithHref;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _RouterLinkActive_31_3:import14.RouterLinkActive;
  _query_RouterLink_31_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_31_1:import15.QueryList<any>;
  _el_32:any;
  _RouterLinkWithHref_32_3:import13.RouterLinkWithHref;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _RouterLinkActive_35_3:import14.RouterLinkActive;
  _query_RouterLink_35_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_35_1:import15.QueryList<any>;
  _el_36:any;
  _RouterLinkWithHref_36_3:import13.RouterLinkWithHref;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  /*private*/ _appEl_48:import2.AppElement;
  _RouterOutlet_48_5:import16.RouterOutlet;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  /*private*/ _appEl_52:import2.AppElement;
  _ErrorComponent_52_4:import17.ErrorComponent;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','navbar navbar-default');
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','container');
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','navbar-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'aria-controls','navbar');
    this.renderer.setElementAttribute(this._el_7,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_7,'class','navbar-toggle collapsed');
    this.renderer.setElementAttribute(this._el_7,'data-target','#navbar');
    this.renderer.setElementAttribute(this._el_7,'data-toggle','collapse');
    this.renderer.setElementAttribute(this._el_7,'type','button');
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','sr-only');
    this._text_10 = this.renderer.createText(this._el_9,'Toggle navigation',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','icon-bar');
    this._text_13 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','icon-bar');
    this._text_15 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','icon-bar');
    this._text_17 = this.renderer.createText(this._el_7,'\n          ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_5,'a',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','navbar-brand');
    this.renderer.setElementAttribute(this._el_19,'routerLink','/home');
    this._RouterLinkWithHref_19_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._text_20 = this.renderer.createText(this._el_19,'Smart Grid',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','collapse navbar-collapse');
    this.renderer.setElementAttribute(this._el_23,'id','navbar');
    this._text_24 = this.renderer.createText(this._el_23,'\n          ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','nav navbar-nav');
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'li',(null as any));
    this.renderer.setElementAttribute(this._el_27,'routerLinkActive','active');
    this._RouterLinkActive_27_3 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import21.ElementRef(this._el_27),this.renderer);
    this._query_RouterLink_27_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_27_1 = new import15.QueryList<any>();
    this._el_28 = this.renderer.createElement(this._el_27,'a',(null as any));
    this.renderer.setElementAttribute(this._el_28,'routerLink','/home');
    this._RouterLinkWithHref_28_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._text_29 = this.renderer.createText(this._el_28,'Home',(null as any));
    this._text_30 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_25,'li',(null as any));
    this.renderer.setElementAttribute(this._el_31,'routerLinkActive','active');
    this._RouterLinkActive_31_3 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import21.ElementRef(this._el_31),this.renderer);
    this._query_RouterLink_31_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_31_1 = new import15.QueryList<any>();
    this._el_32 = this.renderer.createElement(this._el_31,'a',(null as any));
    this.renderer.setElementAttribute(this._el_32,'routerLink','/about');
    this._RouterLinkWithHref_32_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._text_33 = this.renderer.createText(this._el_32,'About',(null as any));
    this._text_34 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_25,'li',(null as any));
    this.renderer.setElementAttribute(this._el_35,'routerLinkActive','active');
    this._RouterLinkActive_35_3 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import21.ElementRef(this._el_35),this.renderer);
    this._query_RouterLink_35_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_35_1 = new import15.QueryList<any>();
    this._el_36 = this.renderer.createElement(this._el_35,'a',(null as any));
    this.renderer.setElementAttribute(this._el_36,'routerLink','/auth');
    this._RouterLinkWithHref_36_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._text_37 = this.renderer.createText(this._el_36,'Authentication',(null as any));
    this._text_38 = this.renderer.createText(this._el_25,'\n          ',(null as any));
    this._text_39 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._text_41 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_43 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','container');
    this._text_44 = this.renderer.createText(this._el_43,'\n  ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','row');
    this._text_46 = this.renderer.createText(this._el_45,'\n    ',(null as any));
    this._text_47 = this.renderer.createText(this._el_45,'\n    ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_45,'router-outlet',(null as any));
    this._appEl_48 = new import2.AppElement(48,45,this,this._el_48);
    this._RouterOutlet_48_5 = new import16.RouterOutlet(this.parentInjector.get(import22.RouterOutletMap),this._appEl_48.vcRef,this.parentInjector.get(import23.ComponentFactoryResolver),(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n  ',(null as any));
    this._text_50 = this.renderer.createText(this._el_43,'\n',(null as any));
    this._text_51 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_52 = this.renderer.createElement(parentRenderNode,'app-error',(null as any));
    this._appEl_52 = new import2.AppElement(52,(null as any),this,this._el_52);
    var compView_52:any = import24.viewFactory_ErrorComponent0(this.viewUtils,this.injector(52),this._appEl_52);
    this._ErrorComponent_52_4 = new import17.ErrorComponent(this.parentInjector.get(import10.ErrorService));
    this._appEl_52.initComponent(this._ErrorComponent_52_4,[],compView_52);
    compView_52.create(this._ErrorComponent_52_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_36,'click',this.eventHandler(this._handle_click_36_0.bind(this)));
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3; }
    if (((token === import13.RouterLinkWithHref) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._RouterLinkWithHref_28_3; }
    if (((token === import14.RouterLinkActive) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._RouterLinkActive_27_3; }
    if (((token === import13.RouterLinkWithHref) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLinkWithHref_32_3; }
    if (((token === import14.RouterLinkActive) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLinkActive_31_3; }
    if (((token === import13.RouterLinkWithHref) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._RouterLinkWithHref_36_3; }
    if (((token === import14.RouterLinkActive) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._RouterLinkActive_35_3; }
    if (((token === import16.RouterOutlet) && (48 === requestNodeIndex))) { return this._RouterOutlet_48_5; }
    if (((token === import17.ErrorComponent) && (52 === requestNodeIndex))) { return this._ErrorComponent_52_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = '/home';
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_19_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_19_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_27_3.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_27_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_5:any = '/home';
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._RouterLinkWithHref_28_3.routerLink = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_28_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_7:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkActive_31_3.routerLinkActive = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_31_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_9:any = '/about';
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._RouterLinkWithHref_32_3.routerLink = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_32_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_11:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._RouterLinkActive_35_3.routerLinkActive = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_35_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_13:any = '/auth';
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RouterLinkWithHref_36_3.routerLink = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_36_3.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ErrorComponent_52_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_27_0.dirty) {
        this._query_RouterLink_27_0.reset([]);
        this._RouterLinkActive_27_3.links = this._query_RouterLink_27_0;
        this._query_RouterLink_27_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_27_1.dirty) {
        this._query_RouterLinkWithHref_27_1.reset([this._RouterLinkWithHref_28_3]);
        this._RouterLinkActive_27_3.linksWithHrefs = this._query_RouterLinkWithHref_27_1;
        this._query_RouterLinkWithHref_27_1.notifyOnChanges();
      }
      if (this._query_RouterLink_31_0.dirty) {
        this._query_RouterLink_31_0.reset([]);
        this._RouterLinkActive_31_3.links = this._query_RouterLink_31_0;
        this._query_RouterLink_31_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_31_1.dirty) {
        this._query_RouterLinkWithHref_31_1.reset([this._RouterLinkWithHref_32_3]);
        this._RouterLinkActive_31_3.linksWithHrefs = this._query_RouterLinkWithHref_31_1;
        this._query_RouterLinkWithHref_31_1.notifyOnChanges();
      }
      if (this._query_RouterLink_35_0.dirty) {
        this._query_RouterLink_35_0.reset([]);
        this._RouterLinkActive_35_3.links = this._query_RouterLink_35_0;
        this._query_RouterLink_35_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_35_1.dirty) {
        this._query_RouterLinkWithHref_35_1.reset([this._RouterLinkWithHref_36_3]);
        this._RouterLinkActive_35_3.linksWithHrefs = this._query_RouterLinkWithHref_35_1;
        this._query_RouterLinkWithHref_35_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_27_3.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_31_3.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_35_3.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_19_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_19,'href',this.viewUtils.sanitizer.sanitize(import25.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._RouterLinkWithHref_28_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_28,'href',this.viewUtils.sanitizer.sanitize(import25.SecurityContext.URL,currVal_6));
      this._expr_6 = currVal_6;
    }
    const currVal_10:any = this._RouterLinkWithHref_32_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_32,'href',this.viewUtils.sanitizer.sanitize(import25.SecurityContext.URL,currVal_10));
      this._expr_10 = currVal_10;
    }
    const currVal_14:any = this._RouterLinkWithHref_36_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_36,'href',this.viewUtils.sanitizer.sanitize(import25.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_19_3.ngOnDestroy();
    this._RouterLinkWithHref_28_3.ngOnDestroy();
    this._RouterLinkActive_27_3.ngOnDestroy();
    this._RouterLinkWithHref_32_3.ngOnDestroy();
    this._RouterLinkActive_31_3.ngOnDestroy();
    this._RouterLinkWithHref_36_3.ngOnDestroy();
    this._RouterLinkActive_35_3.ngOnDestroy();
    this._RouterOutlet_48_5.ngOnDestroy();
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_19_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_28_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_32_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_36_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_36_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('C:/Users/ahooshmand/Projects/MEAN/SmarGrid2/assets/app/app.component.html',0,import11.ViewEncapsulation.None,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}